#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mftdb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class PathDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFileEntry(FileEntry instance);
    partial void UpdateFileEntry(FileEntry instance);
    partial void DeleteFileEntry(FileEntry instance);
    partial void InsertUpdateLog(UpdateLog instance);
    partial void UpdateUpdateLog(UpdateLog instance);
    partial void DeleteUpdateLog(UpdateLog instance);
    partial void InsertFolderEntry(FolderEntry instance);
    partial void UpdateFolderEntry(FolderEntry instance);
    partial void DeleteFolderEntry(FolderEntry instance);
    #endregion
		
		public PathDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PathDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PathDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PathDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FileEntry> FileEntries
		{
			get
			{
				return this.GetTable<FileEntry>();
			}
		}
		
		public System.Data.Linq.Table<UpdateLog> UpdateLogs
		{
			get
			{
				return this.GetTable<UpdateLog>();
			}
		}
		
		public System.Data.Linq.Table<FolderEntry> FolderEntries
		{
			get
			{
				return this.GetTable<FolderEntry>();
			}
		}
	}
	
	[Table(Name="")]
	public partial class FileEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private ulong _frn;
		
		private string _name;
		
		private ulong _parent_frn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfrnChanging(ulong value);
    partial void OnfrnChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onparent_frnChanging(ulong value);
    partial void Onparent_frnChanged();
    #endregion
		
		public FileEntry()
		{
			OnCreated();
		}
		
		[Column(Storage="_frn", IsPrimaryKey=true)]
		public ulong frn
		{
			get
			{
				return this._frn;
			}
			set
			{
				if ((this._frn != value))
				{
					this.OnfrnChanging(value);
					this.SendPropertyChanging();
					this._frn = value;
					this.SendPropertyChanged("frn");
					this.OnfrnChanged();
				}
			}
		}
		
		[Column(Storage="_name", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_parent_frn")]
		public ulong parent_frn
		{
			get
			{
				return this._parent_frn;
			}
			set
			{
				if ((this._parent_frn != value))
				{
					this.Onparent_frnChanging(value);
					this.SendPropertyChanging();
					this._parent_frn = value;
					this.SendPropertyChanged("parent_frn");
					this.Onparent_frnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="")]
	public partial class UpdateLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _USN;
		
		private System.DateTime _build_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSNChanging(long value);
    partial void OnUSNChanged();
    partial void Onbuild_dateChanging(System.DateTime value);
    partial void Onbuild_dateChanged();
    #endregion
		
		public UpdateLog()
		{
			OnCreated();
		}
		
		[Column(Storage="_USN", IsPrimaryKey=true)]
		public long USN
		{
			get
			{
				return this._USN;
			}
			set
			{
				if ((this._USN != value))
				{
					this.OnUSNChanging(value);
					this.SendPropertyChanging();
					this._USN = value;
					this.SendPropertyChanged("USN");
					this.OnUSNChanged();
				}
			}
		}
		
		[Column(Storage="_build_date")]
		public System.DateTime build_date
		{
			get
			{
				return this._build_date;
			}
			set
			{
				if ((this._build_date != value))
				{
					this.Onbuild_dateChanging(value);
					this.SendPropertyChanging();
					this._build_date = value;
					this.SendPropertyChanged("build_date");
					this.Onbuild_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="")]
	public partial class FolderEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private ulong _frn;
		
		private string _name;
		
		private ulong _parent_frn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfrnChanging(ulong value);
    partial void OnfrnChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onparent_frnChanging(ulong value);
    partial void Onparent_frnChanged();
    #endregion
		
		public FolderEntry()
		{
			OnCreated();
		}
		
		[Column(Storage="_frn", IsPrimaryKey=true)]
		public ulong frn
		{
			get
			{
				return this._frn;
			}
			set
			{
				if ((this._frn != value))
				{
					this.OnfrnChanging(value);
					this.SendPropertyChanging();
					this._frn = value;
					this.SendPropertyChanged("frn");
					this.OnfrnChanged();
				}
			}
		}
		
		[Column(Storage="_name", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_parent_frn")]
		public ulong parent_frn
		{
			get
			{
				return this._parent_frn;
			}
			set
			{
				if ((this._parent_frn != value))
				{
					this.Onparent_frnChanging(value);
					this.SendPropertyChanging();
					this._parent_frn = value;
					this.SendPropertyChanged("parent_frn");
					this.Onparent_frnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
