<?xml version="1.0" encoding="utf-8"?>
<Database Class="FileDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="FileDBs">
    <Type Name="FileDB">
      <Column Member="frn" Type="System.UInt64" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="name" Type="System.String" CanBeNull="false" />
      <Column Member="parent_frn" Type="System.UInt64" CanBeNull="false" />
    </Type>
  </Table>
</Database>